storage:
  # Where to store all the data
  storage_path: /var/lib/trecall/storage

  # Where to store snapshots
  snapshots_path: /var/lib/trecall/snapshots

service:
  static_content_dir: /var/lib/trecall/static
